version: '2'

plugins:
  eslint:
    # Code Climate doesn't support our config
    enabled: false

  fixme:
    enabled: true

  shellcheck:
    enabled: true

  stylelint:
    # Code Climate doesn't support our config
    enabled: false
