aliases:
  - &cache-dir
    id: yarn-cache
    run: echo "::set-output name=dir::$(yarn cache dir)"
  - &cache-restore
    uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: v1-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          v1-${{ runner.os }}-yarn-

name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - *cache-dir
      - *cache-restore
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn run test-ci
        env:
          CI: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - *cache-dir
      - *cache-restore
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn run lint
