name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test-ci
        env:
          CI: true
      # Exporting twice makes PurgeCSS work as expected
      - run: yarn run export
      - run: yarn run export
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Purge CDN
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_AUTH }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
